name: Bug Report
description: File a bug report
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: Describe the issue...
    validations:
      required: true
